// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package fake

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// NewMockMachineSetDeployer creates a new instance of MockMachineSetDeployer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMachineSetDeployer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMachineSetDeployer {
	mock := &MockMachineSetDeployer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMachineSetDeployer is an autogenerated mock type for the MachineSetDeployer type
type MockMachineSetDeployer struct {
	mock.Mock
}

type MockMachineSetDeployer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMachineSetDeployer) EXPECT() *MockMachineSetDeployer_Expecter {
	return &MockMachineSetDeployer_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockMachineSetDeployer
func (_mock *MockMachineSetDeployer) Delete(ctx context.Context, machineSet *unstructured.Unstructured) error {
	ret := _mock.Called(ctx, machineSet)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured) error); ok {
		r0 = returnFunc(ctx, machineSet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMachineSetDeployer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMachineSetDeployer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - machineSet
func (_e *MockMachineSetDeployer_Expecter) Delete(ctx interface{}, machineSet interface{}) *MockMachineSetDeployer_Delete_Call {
	return &MockMachineSetDeployer_Delete_Call{Call: _e.mock.On("Delete", ctx, machineSet)}
}

func (_c *MockMachineSetDeployer_Delete_Call) Run(run func(ctx context.Context, machineSet *unstructured.Unstructured)) *MockMachineSetDeployer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstructured.Unstructured))
	})
	return _c
}

func (_c *MockMachineSetDeployer_Delete_Call) Return(err error) *MockMachineSetDeployer_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMachineSetDeployer_Delete_Call) RunAndReturn(run func(ctx context.Context, machineSet *unstructured.Unstructured) error) *MockMachineSetDeployer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByName provides a mock function for the type MockMachineSetDeployer
func (_mock *MockMachineSetDeployer) DeleteByName(ctx context.Context, name string, namespace string) error {
	ret := _mock.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, name, namespace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMachineSetDeployer_DeleteByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByName'
type MockMachineSetDeployer_DeleteByName_Call struct {
	*mock.Call
}

// DeleteByName is a helper method to define mock.On call
//   - ctx
//   - name
//   - namespace
func (_e *MockMachineSetDeployer_Expecter) DeleteByName(ctx interface{}, name interface{}, namespace interface{}) *MockMachineSetDeployer_DeleteByName_Call {
	return &MockMachineSetDeployer_DeleteByName_Call{Call: _e.mock.On("DeleteByName", ctx, name, namespace)}
}

func (_c *MockMachineSetDeployer_DeleteByName_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockMachineSetDeployer_DeleteByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMachineSetDeployer_DeleteByName_Call) Return(err error) *MockMachineSetDeployer_DeleteByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMachineSetDeployer_DeleteByName_Call) RunAndReturn(run func(ctx context.Context, name string, namespace string) error) *MockMachineSetDeployer_DeleteByName_Call {
	_c.Call.Return(run)
	return _c
}

// Deploy provides a mock function for the type MockMachineSetDeployer
func (_mock *MockMachineSetDeployer) Deploy(ctx context.Context, machineSet *unstructured.Unstructured) error {
	ret := _mock.Called(ctx, machineSet)

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured) error); ok {
		r0 = returnFunc(ctx, machineSet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMachineSetDeployer_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type MockMachineSetDeployer_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
//   - ctx
//   - machineSet
func (_e *MockMachineSetDeployer_Expecter) Deploy(ctx interface{}, machineSet interface{}) *MockMachineSetDeployer_Deploy_Call {
	return &MockMachineSetDeployer_Deploy_Call{Call: _e.mock.On("Deploy", ctx, machineSet)}
}

func (_c *MockMachineSetDeployer_Deploy_Call) Run(run func(ctx context.Context, machineSet *unstructured.Unstructured)) *MockMachineSetDeployer_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstructured.Unstructured))
	})
	return _c
}

func (_c *MockMachineSetDeployer_Deploy_Call) Return(err error) *MockMachineSetDeployer_Deploy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMachineSetDeployer_Deploy_Call) RunAndReturn(run func(ctx context.Context, machineSet *unstructured.Unstructured) error) *MockMachineSetDeployer_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkerNodeImage provides a mock function for the type MockMachineSetDeployer
func (_mock *MockMachineSetDeployer) GetWorkerNodeImage(ctx context.Context, machineSet *unstructured.Unstructured, infraID string) (string, error) {
	ret := _mock.Called(ctx, machineSet, infraID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkerNodeImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured, string) (string, error)); ok {
		return returnFunc(ctx, machineSet, infraID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *unstructured.Unstructured, string) string); ok {
		r0 = returnFunc(ctx, machineSet, infraID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *unstructured.Unstructured, string) error); ok {
		r1 = returnFunc(ctx, machineSet, infraID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMachineSetDeployer_GetWorkerNodeImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkerNodeImage'
type MockMachineSetDeployer_GetWorkerNodeImage_Call struct {
	*mock.Call
}

// GetWorkerNodeImage is a helper method to define mock.On call
//   - ctx
//   - machineSet
//   - infraID
func (_e *MockMachineSetDeployer_Expecter) GetWorkerNodeImage(ctx interface{}, machineSet interface{}, infraID interface{}) *MockMachineSetDeployer_GetWorkerNodeImage_Call {
	return &MockMachineSetDeployer_GetWorkerNodeImage_Call{Call: _e.mock.On("GetWorkerNodeImage", ctx, machineSet, infraID)}
}

func (_c *MockMachineSetDeployer_GetWorkerNodeImage_Call) Run(run func(ctx context.Context, machineSet *unstructured.Unstructured, infraID string)) *MockMachineSetDeployer_GetWorkerNodeImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*unstructured.Unstructured), args[2].(string))
	})
	return _c
}

func (_c *MockMachineSetDeployer_GetWorkerNodeImage_Call) Return(s string, err error) *MockMachineSetDeployer_GetWorkerNodeImage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMachineSetDeployer_GetWorkerNodeImage_Call) RunAndReturn(run func(ctx context.Context, machineSet *unstructured.Unstructured, infraID string) (string, error)) *MockMachineSetDeployer_GetWorkerNodeImage_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMachineSetDeployer
func (_mock *MockMachineSetDeployer) List(ctx context.Context) ([]unstructured.Unstructured, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []unstructured.Unstructured
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]unstructured.Unstructured, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []unstructured.Unstructured); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]unstructured.Unstructured)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMachineSetDeployer_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMachineSetDeployer_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx
func (_e *MockMachineSetDeployer_Expecter) List(ctx interface{}) *MockMachineSetDeployer_List_Call {
	return &MockMachineSetDeployer_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockMachineSetDeployer_List_Call) Run(run func(ctx context.Context)) *MockMachineSetDeployer_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMachineSetDeployer_List_Call) Return(unstructureds []unstructured.Unstructured, err error) *MockMachineSetDeployer_List_Call {
	_c.Call.Return(unstructureds, err)
	return _c
}

func (_c *MockMachineSetDeployer_List_Call) RunAndReturn(run func(ctx context.Context) ([]unstructured.Unstructured, error)) *MockMachineSetDeployer_List_Call {
	_c.Call.Return(run)
	return _c
}
