// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package fake

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/api/compute/v1"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// ConfigurePublicIPOnInstance provides a mock function for the type MockInterface
func (_mock *MockInterface) ConfigurePublicIPOnInstance(ctx context.Context, instance *compute.Instance) error {
	ret := _mock.Called(ctx, instance)

	if len(ret) == 0 {
		panic("no return value specified for ConfigurePublicIPOnInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *compute.Instance) error); ok {
		r0 = returnFunc(ctx, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_ConfigurePublicIPOnInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigurePublicIPOnInstance'
type MockInterface_ConfigurePublicIPOnInstance_Call struct {
	*mock.Call
}

// ConfigurePublicIPOnInstance is a helper method to define mock.On call
//   - ctx
//   - instance
func (_e *MockInterface_Expecter) ConfigurePublicIPOnInstance(ctx interface{}, instance interface{}) *MockInterface_ConfigurePublicIPOnInstance_Call {
	return &MockInterface_ConfigurePublicIPOnInstance_Call{Call: _e.mock.On("ConfigurePublicIPOnInstance", ctx, instance)}
}

func (_c *MockInterface_ConfigurePublicIPOnInstance_Call) Run(run func(ctx context.Context, instance *compute.Instance)) *MockInterface_ConfigurePublicIPOnInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*compute.Instance))
	})
	return _c
}

func (_c *MockInterface_ConfigurePublicIPOnInstance_Call) Return(err error) *MockInterface_ConfigurePublicIPOnInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_ConfigurePublicIPOnInstance_Call) RunAndReturn(run func(ctx context.Context, instance *compute.Instance) error) *MockInterface_ConfigurePublicIPOnInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFirewallRule provides a mock function for the type MockInterface
func (_mock *MockInterface) DeleteFirewallRule(ctx context.Context, projectID string, name string) error {
	ret := _mock.Called(ctx, projectID, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFirewallRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, projectID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_DeleteFirewallRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFirewallRule'
type MockInterface_DeleteFirewallRule_Call struct {
	*mock.Call
}

// DeleteFirewallRule is a helper method to define mock.On call
//   - ctx
//   - projectID
//   - name
func (_e *MockInterface_Expecter) DeleteFirewallRule(ctx interface{}, projectID interface{}, name interface{}) *MockInterface_DeleteFirewallRule_Call {
	return &MockInterface_DeleteFirewallRule_Call{Call: _e.mock.On("DeleteFirewallRule", ctx, projectID, name)}
}

func (_c *MockInterface_DeleteFirewallRule_Call) Run(run func(ctx context.Context, projectID string, name string)) *MockInterface_DeleteFirewallRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInterface_DeleteFirewallRule_Call) Return(err error) *MockInterface_DeleteFirewallRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_DeleteFirewallRule_Call) RunAndReturn(run func(ctx context.Context, projectID string, name string) error) *MockInterface_DeleteFirewallRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePublicIPOnInstance provides a mock function for the type MockInterface
func (_mock *MockInterface) DeletePublicIPOnInstance(ctx context.Context, instance *compute.Instance) error {
	ret := _mock.Called(ctx, instance)

	if len(ret) == 0 {
		panic("no return value specified for DeletePublicIPOnInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *compute.Instance) error); ok {
		r0 = returnFunc(ctx, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_DeletePublicIPOnInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePublicIPOnInstance'
type MockInterface_DeletePublicIPOnInstance_Call struct {
	*mock.Call
}

// DeletePublicIPOnInstance is a helper method to define mock.On call
//   - ctx
//   - instance
func (_e *MockInterface_Expecter) DeletePublicIPOnInstance(ctx interface{}, instance interface{}) *MockInterface_DeletePublicIPOnInstance_Call {
	return &MockInterface_DeletePublicIPOnInstance_Call{Call: _e.mock.On("DeletePublicIPOnInstance", ctx, instance)}
}

func (_c *MockInterface_DeletePublicIPOnInstance_Call) Run(run func(ctx context.Context, instance *compute.Instance)) *MockInterface_DeletePublicIPOnInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*compute.Instance))
	})
	return _c
}

func (_c *MockInterface_DeletePublicIPOnInstance_Call) Return(err error) *MockInterface_DeletePublicIPOnInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_DeletePublicIPOnInstance_Call) RunAndReturn(run func(ctx context.Context, instance *compute.Instance) error) *MockInterface_DeletePublicIPOnInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetFirewallRule provides a mock function for the type MockInterface
func (_mock *MockInterface) GetFirewallRule(ctx context.Context, projectID string, name string) (*compute.Firewall, error) {
	ret := _mock.Called(ctx, projectID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetFirewallRule")
	}

	var r0 *compute.Firewall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*compute.Firewall, error)); ok {
		return returnFunc(ctx, projectID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *compute.Firewall); ok {
		r0 = returnFunc(ctx, projectID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*compute.Firewall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetFirewallRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirewallRule'
type MockInterface_GetFirewallRule_Call struct {
	*mock.Call
}

// GetFirewallRule is a helper method to define mock.On call
//   - ctx
//   - projectID
//   - name
func (_e *MockInterface_Expecter) GetFirewallRule(ctx interface{}, projectID interface{}, name interface{}) *MockInterface_GetFirewallRule_Call {
	return &MockInterface_GetFirewallRule_Call{Call: _e.mock.On("GetFirewallRule", ctx, projectID, name)}
}

func (_c *MockInterface_GetFirewallRule_Call) Run(run func(ctx context.Context, projectID string, name string)) *MockInterface_GetFirewallRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInterface_GetFirewallRule_Call) Return(firewall *compute.Firewall, err error) *MockInterface_GetFirewallRule_Call {
	_c.Call.Return(firewall, err)
	return _c
}

func (_c *MockInterface_GetFirewallRule_Call) RunAndReturn(run func(ctx context.Context, projectID string, name string) (*compute.Firewall, error)) *MockInterface_GetFirewallRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type MockInterface
func (_mock *MockInterface) GetInstance(ctx context.Context, zone string, instance string) (*compute.Instance, error) {
	ret := _mock.Called(ctx, zone, instance)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *compute.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*compute.Instance, error)); ok {
		return returnFunc(ctx, zone, instance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *compute.Instance); ok {
		r0 = returnFunc(ctx, zone, instance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*compute.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, zone, instance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type MockInterface_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - ctx
//   - zone
//   - instance
func (_e *MockInterface_Expecter) GetInstance(ctx interface{}, zone interface{}, instance interface{}) *MockInterface_GetInstance_Call {
	return &MockInterface_GetInstance_Call{Call: _e.mock.On("GetInstance", ctx, zone, instance)}
}

func (_c *MockInterface_GetInstance_Call) Run(run func(ctx context.Context, zone string, instance string)) *MockInterface_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInterface_GetInstance_Call) Return(instance1 *compute.Instance, err error) *MockInterface_GetInstance_Call {
	_c.Call.Return(instance1, err)
	return _c
}

func (_c *MockInterface_GetInstance_Call) RunAndReturn(run func(ctx context.Context, zone string, instance string) (*compute.Instance, error)) *MockInterface_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// InsertFirewallRule provides a mock function for the type MockInterface
func (_mock *MockInterface) InsertFirewallRule(ctx context.Context, projectID string, rule *compute.Firewall) error {
	ret := _mock.Called(ctx, projectID, rule)

	if len(ret) == 0 {
		panic("no return value specified for InsertFirewallRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *compute.Firewall) error); ok {
		r0 = returnFunc(ctx, projectID, rule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_InsertFirewallRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertFirewallRule'
type MockInterface_InsertFirewallRule_Call struct {
	*mock.Call
}

// InsertFirewallRule is a helper method to define mock.On call
//   - ctx
//   - projectID
//   - rule
func (_e *MockInterface_Expecter) InsertFirewallRule(ctx interface{}, projectID interface{}, rule interface{}) *MockInterface_InsertFirewallRule_Call {
	return &MockInterface_InsertFirewallRule_Call{Call: _e.mock.On("InsertFirewallRule", ctx, projectID, rule)}
}

func (_c *MockInterface_InsertFirewallRule_Call) Run(run func(ctx context.Context, projectID string, rule *compute.Firewall)) *MockInterface_InsertFirewallRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*compute.Firewall))
	})
	return _c
}

func (_c *MockInterface_InsertFirewallRule_Call) Return(err error) *MockInterface_InsertFirewallRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_InsertFirewallRule_Call) RunAndReturn(run func(ctx context.Context, projectID string, rule *compute.Firewall) error) *MockInterface_InsertFirewallRule_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceHasPublicIP provides a mock function for the type MockInterface
func (_mock *MockInterface) InstanceHasPublicIP(ctx context.Context, instance *compute.Instance) (bool, error) {
	ret := _mock.Called(ctx, instance)

	if len(ret) == 0 {
		panic("no return value specified for InstanceHasPublicIP")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *compute.Instance) (bool, error)); ok {
		return returnFunc(ctx, instance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *compute.Instance) bool); ok {
		r0 = returnFunc(ctx, instance)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *compute.Instance) error); ok {
		r1 = returnFunc(ctx, instance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_InstanceHasPublicIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceHasPublicIP'
type MockInterface_InstanceHasPublicIP_Call struct {
	*mock.Call
}

// InstanceHasPublicIP is a helper method to define mock.On call
//   - ctx
//   - instance
func (_e *MockInterface_Expecter) InstanceHasPublicIP(ctx interface{}, instance interface{}) *MockInterface_InstanceHasPublicIP_Call {
	return &MockInterface_InstanceHasPublicIP_Call{Call: _e.mock.On("InstanceHasPublicIP", ctx, instance)}
}

func (_c *MockInterface_InstanceHasPublicIP_Call) Run(run func(ctx context.Context, instance *compute.Instance)) *MockInterface_InstanceHasPublicIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*compute.Instance))
	})
	return _c
}

func (_c *MockInterface_InstanceHasPublicIP_Call) Return(b bool, err error) *MockInterface_InstanceHasPublicIP_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockInterface_InstanceHasPublicIP_Call) RunAndReturn(run func(ctx context.Context, instance *compute.Instance) (bool, error)) *MockInterface_InstanceHasPublicIP_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstances provides a mock function for the type MockInterface
func (_mock *MockInterface) ListInstances(ctx context.Context, zone string) (*compute.InstanceList, error) {
	ret := _mock.Called(ctx, zone)

	if len(ret) == 0 {
		panic("no return value specified for ListInstances")
	}

	var r0 *compute.InstanceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*compute.InstanceList, error)); ok {
		return returnFunc(ctx, zone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *compute.InstanceList); ok {
		r0 = returnFunc(ctx, zone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*compute.InstanceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, zone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_ListInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstances'
type MockInterface_ListInstances_Call struct {
	*mock.Call
}

// ListInstances is a helper method to define mock.On call
//   - ctx
//   - zone
func (_e *MockInterface_Expecter) ListInstances(ctx interface{}, zone interface{}) *MockInterface_ListInstances_Call {
	return &MockInterface_ListInstances_Call{Call: _e.mock.On("ListInstances", ctx, zone)}
}

func (_c *MockInterface_ListInstances_Call) Run(run func(ctx context.Context, zone string)) *MockInterface_ListInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInterface_ListInstances_Call) Return(instanceList *compute.InstanceList, err error) *MockInterface_ListInstances_Call {
	_c.Call.Return(instanceList, err)
	return _c
}

func (_c *MockInterface_ListInstances_Call) RunAndReturn(run func(ctx context.Context, zone string) (*compute.InstanceList, error)) *MockInterface_ListInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListZones provides a mock function for the type MockInterface
func (_mock *MockInterface) ListZones(ctx context.Context) (*compute.ZoneList, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListZones")
	}

	var r0 *compute.ZoneList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*compute.ZoneList, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *compute.ZoneList); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*compute.ZoneList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_ListZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListZones'
type MockInterface_ListZones_Call struct {
	*mock.Call
}

// ListZones is a helper method to define mock.On call
//   - ctx
func (_e *MockInterface_Expecter) ListZones(ctx interface{}) *MockInterface_ListZones_Call {
	return &MockInterface_ListZones_Call{Call: _e.mock.On("ListZones", ctx)}
}

func (_c *MockInterface_ListZones_Call) Run(run func(ctx context.Context)) *MockInterface_ListZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInterface_ListZones_Call) Return(zoneList *compute.ZoneList, err error) *MockInterface_ListZones_Call {
	_c.Call.Return(zoneList, err)
	return _c
}

func (_c *MockInterface_ListZones_Call) RunAndReturn(run func(ctx context.Context) (*compute.ZoneList, error)) *MockInterface_ListZones_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFirewallRule provides a mock function for the type MockInterface
func (_mock *MockInterface) UpdateFirewallRule(ctx context.Context, projectID string, name string, rule *compute.Firewall) error {
	ret := _mock.Called(ctx, projectID, name, rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFirewallRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *compute.Firewall) error); ok {
		r0 = returnFunc(ctx, projectID, name, rule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_UpdateFirewallRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFirewallRule'
type MockInterface_UpdateFirewallRule_Call struct {
	*mock.Call
}

// UpdateFirewallRule is a helper method to define mock.On call
//   - ctx
//   - projectID
//   - name
//   - rule
func (_e *MockInterface_Expecter) UpdateFirewallRule(ctx interface{}, projectID interface{}, name interface{}, rule interface{}) *MockInterface_UpdateFirewallRule_Call {
	return &MockInterface_UpdateFirewallRule_Call{Call: _e.mock.On("UpdateFirewallRule", ctx, projectID, name, rule)}
}

func (_c *MockInterface_UpdateFirewallRule_Call) Run(run func(ctx context.Context, projectID string, name string, rule *compute.Firewall)) *MockInterface_UpdateFirewallRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*compute.Firewall))
	})
	return _c
}

func (_c *MockInterface_UpdateFirewallRule_Call) Return(err error) *MockInterface_UpdateFirewallRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_UpdateFirewallRule_Call) RunAndReturn(run func(ctx context.Context, projectID string, name string, rule *compute.Firewall) error) *MockInterface_UpdateFirewallRule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInstanceNetworkTags provides a mock function for the type MockInterface
func (_mock *MockInterface) UpdateInstanceNetworkTags(ctx context.Context, project string, zone string, instance string, tags *compute.Tags) error {
	ret := _mock.Called(ctx, project, zone, instance, tags)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInstanceNetworkTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *compute.Tags) error); ok {
		r0 = returnFunc(ctx, project, zone, instance, tags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_UpdateInstanceNetworkTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInstanceNetworkTags'
type MockInterface_UpdateInstanceNetworkTags_Call struct {
	*mock.Call
}

// UpdateInstanceNetworkTags is a helper method to define mock.On call
//   - ctx
//   - project
//   - zone
//   - instance
//   - tags
func (_e *MockInterface_Expecter) UpdateInstanceNetworkTags(ctx interface{}, project interface{}, zone interface{}, instance interface{}, tags interface{}) *MockInterface_UpdateInstanceNetworkTags_Call {
	return &MockInterface_UpdateInstanceNetworkTags_Call{Call: _e.mock.On("UpdateInstanceNetworkTags", ctx, project, zone, instance, tags)}
}

func (_c *MockInterface_UpdateInstanceNetworkTags_Call) Run(run func(ctx context.Context, project string, zone string, instance string, tags *compute.Tags)) *MockInterface_UpdateInstanceNetworkTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*compute.Tags))
	})
	return _c
}

func (_c *MockInterface_UpdateInstanceNetworkTags_Call) Return(err error) *MockInterface_UpdateInstanceNetworkTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_UpdateInstanceNetworkTags_Call) RunAndReturn(run func(ctx context.Context, project string, zone string, instance string, tags *compute.Tags) error) *MockInterface_UpdateInstanceNetworkTags_Call {
	_c.Call.Return(run)
	return _c
}
