---
dir: fake
pkgname: fake
filename: client.go
template: testify
template-data:
  boilerplate-file: ../../../.header
packages:
  github.com/submariner-io/cloud-prepare/pkg/gcp/client:
    interfaces:
      Interface: {}
