---
dir: fake
pkgname: fake
filename: machineset.go
template: testify
template-data:
  boilerplate-file: ../../.header
packages:
  github.com/submariner-io/cloud-prepare/pkg/ocp:
    interfaces:
      MachineSetDeployer: {}
